name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login DockerHub
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build the Docker image
      run: docker build . --tag danccooper/get-iplayer:latest
    - name: Tag as latest
      run: docker tag danccooper/get-iplayer:latest danccooper/get-iplayer:$(date +%s)
    - name: Push images
      run: docker push danccooper/get-iplayer:$(date +%s) && docker push danccooper/get-iplayer:latest
